---
scan_for_new_leads_in_salesforce:
  agent: lead_ingestion_agent
  description: |
    Find up to 5 leads with Status = 'New' in Salesforce and extract all fields.

    Extract these fields: Name, Title, Email, Phone, Role__c, Industry, Company, Address, Website, Lead_Source_Site__c, AnnualRevenue, Annual_Number_of_Homes__c, Lead_Score__c

    Return null for empty fields. Only process 5 records. 

  expected_output: |
    JSON array containing up to 5 lead objects, each with lead_id and all fields (null if empty).


enrich_missing_lead_fields:
  agent: lead_enrichment_agent
  description: |
    Enrich null fields for all leads using web search. Process each lead individually. Do not overwrite existing data.

    Use SERPER and web scraping to find: Title, Role__c, Industry, Website, Address, AnnualRevenue, Annual_Number_of_Homes__c.

  expected_output: |
    JSON array with all leads containing enriched fields filled in.


validate_enriched_lead_data:
  agent: qa_data_verification_agent
  description: |
    Verify enriched data accuracy for all leads. Check for inconsistencies and flag unreliable fields.

  expected_output: |
    JSON array with all leads containing validated fields.

score_lead_quality:
  agent: lead_scoring_agent
  description: |
    Calculate Lead_Score__c for all leads using this scoring:

    Basic Info: First/Last Name (5 each), Title (5), Company (5), Address (10), Email (5), Phone (5), Website (5)
    Business: Annual_Number_of_Homes__c (0-10), Employees (0-5)  
    Industry: Hospitality/Multi Family/Single Family (10), others (5)
    Role: Architect/Designer/Plumber (10), others (5)
    Penalty: Email Opt-Out (-20)

    Sum points (0-100 max).
    
    IMPORTANT: Return the score as a whole number (integer) for Salesforce Number(18,0) field.

  expected_output: |
    JSON array with all leads containing Score field (integer 0-100) and scoring breakdown.

update_leads_and_mark_as_reviewed:
  agent: salesforce_integration_agent
  description: |
    Update Salesforce for all leads with these exact field mappings:

    Standard fields: Title, Email, Phone, Industry, Website, Street, City, State, PostalCode, CountryCode
    Custom fields: Role__c, AnnualRevenue, Annual_Number_of_Homes__c, Lead_Score__c, AI_Enriched__c, Status

    CRITICAL FIELD UPDATES:
    - Status: Use 'Enriched'
    - AI_Enriched__c: Set to true (boolean value for checkbox)
    - Lead_Score__c: Use whole number only (no decimals) - round the score to nearest integer
    - AnnualRevenue: numerical string only
    - CountryCode: 'US'
    
    DATA TYPE REQUIREMENTS:
    - Status: Must match exact picklist value (case-sensitive)
    - AI_Enriched__c: Boolean true/false
    - Lead_Score__c: Integer only (Number(18,0) field)
    - Industry: Must be from picklist (Education, Government/Military, Healthcare, Hospitality, Mixed Use Dev, Multi Family, Office Building, Prison, Religious/Cultural Facilities, Restaurant/Retail, Ship, Single Family, Stadium/Entertainment). If industry value doesn't match exactly, select the most relevant choice from the picklist.
    - Role__c: Must be from picklist (Architect, Builder, Civil Engineer, Contractor, Developer, Engineer, General Contractor, General Manager, Installer/Plumber, Mechanical Contractor, Mechanical Engineer, Property Manager, Structural Engineer, Owner, Project Manager, Purchaser/Buyer). If role value doesn't match exactly, select the most relevant choice from the picklist.
    
    
    DEBUGGING STEPS:
    - If update fails, check field-level security permissions
    - Verify the exact API field names match Salesforce exactly
    - Test with minimal field set first (just one field at a time)
    
    NOTE: If Role__c enum fails, skip it and continue with other fields.
    
    Process all leads in the batch and provide individual status for each.

  expected_output: |
    Report showing updated fields and confirmations for all processed leads.


